name: EC2 Setup

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  KEY_NAME: andy-test

jobs:
  setup-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Get EC2 Instance Info
        id: ec2_info
        run: |
          terraform output -raw  > instance_id.txt
          cat instance_id.txt
          echo "instance_id=$(cat instance_id.txt)" >> $GITHUB_ENV
