name: EC2 Setup

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  KEY_NAME: andy-test

jobs:
  setup-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform plan -var="key_name=${{ env.KEY_NAME }}"

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve -var="key_name=${{ env.KEY_NAME }}"

      - name: Get EC2 Instance Info
        run: |
          terraform output -json >> $GITHUB_OUTPUT
